### ISSUE TITLE
为什么我老是调试这个错误，我用的qt5.15.2和vs2019

### ISSUE THREAD

**Issue by 519984307** [yuekeyuans/IWebCore#5]
![捕获](https://github.com/yuekeyuans/IWebCore/assets/39296638/719c008b-a16a-4b67-9234-396165c7cc35)

**Comment by yuekeyuans** [comment]
用 5.14.2吧，我其他的版本还没试过，这个版本能直接离线安装，我一直用的是这个

**Comment by yuekeyuans** [comment]
![image](https://github.com/yuekeyuans/IWebCore/assets/60599728/98c74561-b15f-483a-a1a8-c8e69c6ca94b)
你是2022年发消息的那个人么？

**Comment by 519984307** [comment]
是的呀






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月8日(星期五) 中午1:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuekeyuans/IWebCore] 为什么我老是调试这个错误，我用的qt5.15.2和vs2019 (Issue #5)





 
image.png (view on web)
 你是2022年发消息的那个人么？

**Comment by yuekeyuans** [comment]
哦哦， 你是干什么的啊，需要用的这个东西么？ 我能帮什么的吗？

**Comment by 519984307** [comment]
我看这个也是为了学习，做自动化的设备的，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuekeyuans/IWebCore] 为什么我老是调试这个错误，我用的qt5.15.2和vs2019 (Issue #5)




 
哦哦， 你是干什么的啊，需要用的这个东西么？ 我能帮什么的吗？

**Comment by 519984307** [comment]
我在杭州你在哪儿呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月8日(周五) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuekeyuans/IWebCore] 为什么我老是调试这个错误，我用的qt5.15.2和vs2019 (Issue #5)




 
哦哦， 你是干什么的啊，需要用的这个东西么？ 我能帮什么的吗？

**Comment by yuekeyuans** [comment]
合肥
